### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by davidanthoff** [xiaodaigh/fstformat.jl#1]
Would be great if you could register this package in METADATA.jl. Once that is done, I'll register https://github.com/davidanthoff/FstFiles.jl, which brings the full FileIO.jl/iterable tables/query integration along.

**Comment by xiaodaigh** [comment]
I am not sure if I should register it until I have a native binding that doesn't go through R.

**Comment by davidanthoff** [comment]
It seems useful as is? Sure, not super fast, but still. If a registered package becomes much faster later, everyone will be happy :) I'd go with a registration, I don't think there is any harm.

**Comment by davidanthoff** [comment]
Bump, I do think it would be useful if this was registered, even if slow. Any chance you might be able to register the package? Let me know if I can help somehow.

**Comment by phillc73** [comment]
A bit pointless to say +1, but I would love to be able to use Query.jl on fst files in Julia.

**Comment by xiaodaigh** [comment]
https://github.com/JuliaRegistries/General/pull/2477

I have tried to register it. Do I need to do anything further?

**Comment by davidanthoff** [comment]
I think you just need to wait, all looks good to me!

Thanks :)

**Comment by xiaodaigh** [comment]
Done https://github.com/JuliaRegistries/General/pull/2477
