### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by davidanthoff** [xiaodaigh/fstformat.jl#6]
Can you enable travis and appveyor for this repo?

**Comment by xiaodaigh** [comment]
I tried to log in and they are "enabled". Not sure how to check. Also is there a guide on how to do this CI stuff for Julia? I can read up on this https://docs.travis-ci.com/user/languages/julia/

**Comment by davidanthoff** [comment]
Hm, strange, because no CI results are showing up here in the repo... I'm not aware of any documentation for that stuff.
